image:
    name: nimlang/nim:alpine

pipelines:
    default:
        - step:
            script:
                - nimble refresh
                - nimble build
                - nimble develop
                - nimble tests