image:
    name: nimlang/nim:alpine

pipelines:
    default:
        - step:
            name: 'Stable'
            script: &tests
                - nim --version
                - nimble refresh
                - nimble build
                - nimble develop
                - nimble tests
        - step:
            name: 'nim-1.4.8'
            image: nimlang/nim:1.4.8-alpine
            script: *tests
        - step:
            name: 'nim-1.2.18'
            image: nimlang/nim:1.2.18-alpine
            script: *tests
        - step:
            name: 'nim-1.0.10'
            image: nimlang/nim:1.0.0-alpine
            script: *tests