image:
    name: nimlang/nim:alpine

pipelines:
    default:
        - step:
            name: 'Stable'
            script:
                - nimble refresh
                - nimble build
                - nimble develop
                - nimble tests
        - step:
            name: 'nim-1.0.0'
            image: nimlang/nim:1.0.0-alpine
            script:
                - nimble refresh
                - nimble build
                - nimble develop
                - nimble tests